Qf-2008 provider view for employer requests
SkillsFundingAgency/das-rat-api pull request #11
Opened 2024-06-26 14:28 UTC by karen-hanna

2024-06-27 17:01 UTC, dashton82 approved these changes
Looks good - but unsure as to why we need to persist course/standard information but I'm guessing its out of the scope of this PR 😁

2024-07-01 10:15 UTC, ChrisJWoodcock requested changes

2024-07-01 10:15 UTC, ChrisJWoodcock commented on src/SFA.DAS.RequestApprenticeTraining.Application/Queries/GetAggregatedEmployerRequests/GeAggregatedtEmployerRequestsQueryResult.cs
> +﻿using System.Collections.Generic;
File name typo

2024-07-01 10:15 UTC, ChrisJWoodcock commented on src/SFA.DAS.RequestApprenticeTraining.Domain/Entities/EmployerRequest.cs
> +        public virtual Standard Standard { get; set; }
What is the purpose of virtual here?

2024-07-11 14:16 UTC, ChrisJWoodcock commented on src/SFA.DAS.RequestApprenticeTraining.Domain/Entities/EmployerRequest.cs
> +        public virtual Standard Standard { get; set; }
I've removed the virtual

2024-07-11 14:18 UTC, ChrisJWoodcock commented on src/SFA.DAS.RequestApprenticeTraining.Application/Queries/GetAggregatedEmployerRequests/GeAggregatedtEmployerRequestsQueryResult.cs
> +﻿using System.Collections.Generic;
Fixed

2024-07-11 14:18 UTC, ChrisJWoodcock approved these changes

2024-08-01 14:47 UTC, ChrisJWoodcock commented
This has been superseded by https://github.com/SkillsFundingAgency/das-rat-api/pull/16

2024-08-01 14:47 UTC, closed without merging