QF-2008-Inner-API-Latest
SkillsFundingAgency/das-rat-api pull request #16
Opened 2024-07-23 13:15 UTC by karen-hanna

2024-08-01 15:49 UTC, ChrisJWoodcock requested changes

2024-08-01 15:49 UTC, ChrisJWoodcock commented on src/SFA.DAS.RequestApprenticeTraining.Application/Queries/GetAggregatedEmployerRequests/GetAggregatedEmployerRequestsQueryHandler.cs
> +                    aggregatedRequests.Select(entity => entity).ToList()
What is this doing entity => entity?

2024-08-05 15:02 UTC, ChrisJWoodcock approved these changes

2024-08-07 08:17 UTC, karen-hanna commented on src/SFA.DAS.RequestApprenticeTraining.Application/Queries/GetAggregatedEmployerRequests/GetAggregatedEmployerRequestsQueryHandler.cs
> +                    aggregatedRequests.Select(entity => entity).ToList()
Fixed

2024-08-14 14:19 UTC, merged