QF-2009-select-requests-inner-api
SkillsFundingAgency/das-rat-api pull request #17
Opened 2024-07-30 08:28 UTC by karen-hanna

2024-08-05 16:13 UTC, ChrisJWoodcock requested changes

2024-08-05 16:13 UTC, ChrisJWoodcock commented on src/SFA.DAS.RequestApprenticeTraining.Api/Controllers/EmployerRequestController.cs
> +                _logger.LogError(ex, $"Validation error attempting to retrieve employer request for Ukprn: {accountId} and StandardReference: {standardReference.SanitizeLogData()}");
Why has this changed to Ukprn - still passing an AccountId

2024-08-05 16:13 UTC, ChrisJWoodcock commented on src/SFA.DAS.RequestApprenticeTraining.Application/Commands/CreateProviderResponseEmployerRequests/CreateProviderResponseEmployerRequestsCommandHandler.cs
> +                foreach (var employerRequestId in request.EmployerRequestIds)
How does this check that the response from the same provider does not already exist?

2024-08-05 16:13 UTC, ChrisJWoodcock commented on src/SFA.DAS.RequestApprenticeTraining.Application/Commands/CreateProviderResponseEmployerRequests/CreateProviderResponseEmployerRequestsCommandHandler.cs
> +                var x = ex.InnerException;
?

2024-08-05 16:13 UTC, ChrisJWoodcock commented on src/SFA.DAS.RequestApprenticeTraining.Application/Commands/CreateProviderResponseEmployerRequests/CreateProviderResponseEmployerRequestsCommandHandler.cs
> +            return new CreateProviderResponseEmployerRequestsCommandResponse() { Result = true};
This will always return true - so it doesn't really return anything - I see in the outer that it can also return a Boolean result which would be unnecessary

2024-08-05 16:13 UTC, ChrisJWoodcock commented on src/SFA.DAS.RequestApprenticeTraining.Application/Queries/GetAggregatedEmployerRequests/GetAggregatedEmployerRequestsQueryHandler.cs
> -                    aggregatedRequests.Select(entity => entity).ToList()
I think this is out of sync with 2008 as seeing same changes twice

2024-08-05 16:13 UTC, ChrisJWoodcock commented on src/SFA.DAS.RequestApprenticeTraining.Domain/Interfaces/IEmployerRequestEntityContext.cs
> +        public async Task<List<SelectEmployerRequest>> GetForStandard(long ukprn, string standardReference)
GetForProviderAndStandard? maybe

2024-08-06 13:15 UTC, karen-hanna commented on src/SFA.DAS.RequestApprenticeTraining.Api/Controllers/EmployerRequestController.cs
> +                _logger.LogError(ex, $"Validation error attempting to retrieve employer request for Ukprn: {accountId} and StandardReference: {standardReference.SanitizeLogData()}");
Change reverted

2024-08-06 13:30 UTC, karen-hanna commented on src/SFA.DAS.RequestApprenticeTraining.Application/Commands/CreateProviderResponseEmployerRequests/CreateProviderResponseEmployerRequestsCommandHandler.cs
> +            return new CreateProviderResponseEmployerRequestsCommandResponse() { Result = true};
removed return value

2024-08-06 13:33 UTC, karen-hanna commented on src/SFA.DAS.RequestApprenticeTraining.Application/Queries/GetAggregatedEmployerRequests/GetAggregatedEmployerRequestsQueryHandler.cs
> -                    aggregatedRequests.Select(entity => entity).ToList()
there were pending merges. the code is now in sync

2024-08-06 13:34 UTC, karen-hanna commented on src/SFA.DAS.RequestApprenticeTraining.Domain/Interfaces/IEmployerRequestEntityContext.cs
> +        public async Task<List<SelectEmployerRequest>> GetForStandard(long ukprn, string standardReference)
renamed

2024-08-06 13:38 UTC, karen-hanna commented on src/SFA.DAS.RequestApprenticeTraining.Application/Commands/CreateProviderResponseEmployerRequests/CreateProviderResponseEmployerRequestsCommandHandler.cs
> +                var x = ex.InnerException;
removed

2024-08-07 08:09 UTC, karen-hanna commented on src/SFA.DAS.RequestApprenticeTraining.Application/Commands/CreateProviderResponseEmployerRequests/CreateProviderResponseEmployerRequestsCommandHandler.cs
> +                foreach (var employerRequestId in request.EmployerRequestIds)
I've added a CreateIfNotExistsAsync method to the entity which checks before creating

2024-08-08 10:42 UTC, ChrisJWoodcock approved these changes, later dismissed

2024-08-14 14:22 UTC, ChrisJWoodcock approved these changes, later dismissed

2024-08-16 13:08 UTC, ChrisJWoodcock approved these changes

2024-08-16 13:09 UTC, merged