QF-2068-Provider_confirmation_api
SkillsFundingAgency/das-rat-api pull request #20
Opened 2024-08-20 14:12 UTC by karen-hanna

2024-08-28 12:59 UTC, ChrisJWoodcock requested changes

2024-08-28 12:59 UTC, ChrisJWoodcock commented on src/SFA.DAS.RequestApprenticeTraining.Api/Controllers/EmployerRequestController.cs
> +                _logger.LogError(e, $"Error attempting to retrieve sprovider response confirmation");
typo sprovider

2024-08-28 13:00 UTC, ChrisJWoodcock commented
See the sonar cloud issue

2024-08-28 14:04 UTC, karen-hanna commented on src/SFA.DAS.RequestApprenticeTraining.Api/Controllers/EmployerRequestController.cs
> +                _logger.LogError(e, $"Error attempting to retrieve sprovider response confirmation");
Fixed

2024-08-28 16:00 UTC, ChrisJWoodcock approved these changes, later dismissed

2024-09-02 11:40 UTC, ChrisJWoodcock approved these changes

2024-09-02 11:45 UTC, merged